// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SunFilled from '/Users/yzzer/workspace/repos/fedlog-fe/node_modules/@ant-design/icons/es/icons/SunFilled';
import ProjectOutlined from '/Users/yzzer/workspace/repos/fedlog-fe/node_modules/@ant-design/icons/es/icons/ProjectOutlined';
import ContainerOutlined from '/Users/yzzer/workspace/repos/fedlog-fe/node_modules/@ant-design/icons/es/icons/ContainerOutlined';
import ExperimentOutlined from '/Users/yzzer/workspace/repos/fedlog-fe/node_modules/@ant-design/icons/es/icons/ExperimentOutlined';
import DeploymentUnitOutlined from '/Users/yzzer/workspace/repos/fedlog-fe/node_modules/@ant-design/icons/es/icons/DeploymentUnitOutlined';
import DashboardOutlined from '/Users/yzzer/workspace/repos/fedlog-fe/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import UserOutlined from '/Users/yzzer/workspace/repos/fedlog-fe/node_modules/@ant-design/icons/es/icons/UserOutlined';
export default { SunFilled, ProjectOutlined, ContainerOutlined, ExperimentOutlined, DeploymentUnitOutlined, DashboardOutlined, UserOutlined };
