// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SunFilled from '/Users/yzzer/workspace/repos/fedlog-fe/node_modules/@ant-design/icons/es/icons/SunFilled';
import SmileOutlined from '/Users/yzzer/workspace/repos/fedlog-fe/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import DashboardOutlined from '/Users/yzzer/workspace/repos/fedlog-fe/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import FormOutlined from '/Users/yzzer/workspace/repos/fedlog-fe/node_modules/@ant-design/icons/es/icons/FormOutlined';
import TableOutlined from '/Users/yzzer/workspace/repos/fedlog-fe/node_modules/@ant-design/icons/es/icons/TableOutlined';
import UserOutlined from '/Users/yzzer/workspace/repos/fedlog-fe/node_modules/@ant-design/icons/es/icons/UserOutlined';
export default { SunFilled, SmileOutlined, DashboardOutlined, FormOutlined, TableOutlined, UserOutlined };
