// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/Users/yzzer/workspace/repos/fedlog-fe/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import DashboardOutlined from '/Users/yzzer/workspace/repos/fedlog-fe/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import FormOutlined from '/Users/yzzer/workspace/repos/fedlog-fe/node_modules/@ant-design/icons/es/icons/FormOutlined';
import TableOutlined from '/Users/yzzer/workspace/repos/fedlog-fe/node_modules/@ant-design/icons/es/icons/TableOutlined';
import ProfileOutlined from '/Users/yzzer/workspace/repos/fedlog-fe/node_modules/@ant-design/icons/es/icons/ProfileOutlined';
import CheckCircleOutlined from '/Users/yzzer/workspace/repos/fedlog-fe/node_modules/@ant-design/icons/es/icons/CheckCircleOutlined';
import WarningOutlined from '/Users/yzzer/workspace/repos/fedlog-fe/node_modules/@ant-design/icons/es/icons/WarningOutlined';
import UserOutlined from '/Users/yzzer/workspace/repos/fedlog-fe/node_modules/@ant-design/icons/es/icons/UserOutlined';
export default { SmileOutlined, DashboardOutlined, FormOutlined, TableOutlined, ProfileOutlined, CheckCircleOutlined, WarningOutlined, UserOutlined };
