// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/yzzer/workspace/repos/fedlog-fe/src/pages/model-training/models/index';
import model_2 from '/Users/yzzer/workspace/repos/fedlog-fe/src/.umi/plugin-initialState/@@initialState';

export const models = {
model_1: { namespace: 'model-training.index', model: model_1 },
model_2: { namespace: '@@initialState', model: model_2 },
} as const
